### ISSUE TITLE
Contrast Issues in several areas

### ISSUE THREAD

**Issue by QTMcKay** [taniarascia/new-moon-chrome-devtools#1]
First, LOVE your extension!

There still exists black text on dark background in certain areas:

 - Elements: Event Listeners
 - Sources: source folder pane
 - Network: Headers Tab

And light-gray text on white backgrounds in other areas:

 - Sources: Watch/Callstack/Breakpoints/etc pane
 - Network: options bar
 - Application: Local Storage > selected values

Probably other areas have these contrast issues as well, but those are the areas I noticed in the first few minutes.

Suggestion: why not make the background _pure_ black instead of "almost" black? ;)  Better contrast overall!

![image](https://user-images.githubusercontent.com/22524639/39730697-63ffc53e-5220-11e8-9716-41d26cd7f37d.png)

![image](https://user-images.githubusercontent.com/22524639/39730707-74a8fc66-5220-11e8-9348-fb2700f5182b.png)

![image](https://user-images.githubusercontent.com/22524639/39730719-81306136-5220-11e8-8a00-0f664f752d90.png)

![image](https://user-images.githubusercontent.com/22524639/39730737-99024e82-5220-11e8-9fda-ccb5e260a44f.png)

**Comment by taniarascia** [comment]
Thank you for letting me know! I'll work on fixing these areas with poor contrast.

**Comment by taniarascia** [comment]
I think all of these have been addressed as long as you're on dark theme. I can't replicate any of these anymore.
